Repository ChungBazi/ChungBazi-BE, pull requests merged in 2025-01, with the labels that each got.

#2 [chore] issue, pr template 생성
  .github/ISSUE_TEMPLATE/⚙️-chore-template.md
  .github/ISSUE_TEMPLATE/🔧-fix-template.md
  .github/ISSUE_TEMPLATE/🔨-refactor-template.md
  .github/ISSUE_TEMPLATE/🛠️-feature-template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: :page_facing_up: docs

#7 [chore] swagger setting
  build.gradle
  src/main/java/chungbazi/chungbazi_be/global/config/SwaggerConfig.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ⚙ chore

#4 [chore] 응답 통일, 예외 처리 설정
  src/main/java/chungbazi/chungbazi_be/global/apiPayload/ApiResponse.java
  src/main/java/chungbazi/chungbazi_be/global/apiPayload/code/BaseCode.java
  src/main/java/chungbazi/chungbazi_be/global/apiPayload/code/BaseErrorCode.java
  src/main/java/chungbazi/chungbazi_be/global/apiPayload/code/ErrorReasonDTO.java
  src/main/java/chungbazi/chungbazi_be/global/apiPayload/code/ReasonDTO.java
  src/main/java/chungbazi/chungbazi_be/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/chungbazi/chungbazi_be/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/chungbazi/chungbazi_be/global/apiPayload/exception/ExceptionAdvice.java
  src/main/java/chungbazi/chungbazi_be/global/apiPayload/exception/GeneralException.java
Labels: ⚙ chore

#11 [chore] Spring Security 설정 정보 위치 이동
  src/main/java/chungbazi/chungbazi_be/domain/auth/CustomUserDetailService.java
  src/main/java/chungbazi/chungbazi_be/global/config/SecurityConfig.java
Labels: ⚙ chore, 🏛 reconstruct

#16 [feature] Member 도메인 클래스 생성 및 필드 정의
  src/main/java/chungbazi/chungbazi_be/domain/auth/CustomUserDetailService.java
  src/main/java/chungbazi/chungbazi_be/domain/member/MemberHandler.java
  src/main/java/chungbazi/chungbazi_be/domain/member/controller/MemberController.java
  src/main/java/chungbazi/chungbazi_be/domain/member/dto/MemberRequestDTO.java
  src/main/java/chungbazi/chungbazi_be/domain/member/dto/MemberResponseDTO.java
  src/main/java/chungbazi/chungbazi_be/domain/member/entity/Addition.java
  src/main/java/chungbazi/chungbazi_be/domain/member/entity/Interest.java
  src/main/java/chungbazi/chungbazi_be/domain/member/entity/Member.java
  src/main/java/chungbazi/chungbazi_be/domain/member/entity/enums/Education.java
  src/main/java/chungbazi/chungbazi_be/domain/member/entity/enums/Employment.java
  src/main/java/chungbazi/chungbazi_be/domain/member/entity/enums/Gender.java
  src/main/java/chungbazi/chungbazi_be/domain/member/entity/enums/Income.java
  src/main/java/chungbazi/chungbazi_be/domain/member/entity/enums/OAuthProvider.java
  src/main/java/chungbazi/chungbazi_be/domain/member/entity/enums/Region.java
  src/main/java/chungbazi/chungbazi_be/domain/member/entity/mapping/MemberAddition.java
  src/main/java/chungbazi/chungbazi_be/domain/member/entity/mapping/MemberInterest.java
  src/main/java/chungbazi/chungbazi_be/domain/member/repository/AdditionRepository.java
  src/main/java/chungbazi/chungbazi_be/domain/member/repository/InterestRepository.java
  src/main/java/chungbazi/chungbazi_be/domain/member/repository/MemberAdditionRepository.java
  src/main/java/chungbazi/chungbazi_be/domain/member/repository/MemberInterestRepository.java
  src/main/java/chungbazi/chungbazi_be/domain/member/repository/MemberRepository.java
  src/main/java/chungbazi/chungbazi_be/domain/member/service/MemberService.java
  src/main/java/chungbazi/chungbazi_be/global/apiPayload/code/status/ErrorStatus.java
Labels: 🛠 feature

#21 [feature] 프로필 정보 조회 및 security 설정
  .DS_Store
  build.gradle
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/chungbazi/chungbazi_be/domain/member/controller/MemberController.java
  src/main/java/chungbazi/chungbazi_be/domain/member/dto/MemberResponseDTO.java
  src/main/java/chungbazi/chungbazi_be/domain/member/entity/enums/OAuthProvider.java
  src/main/java/chungbazi/chungbazi_be/domain/member/repository/MemberAdditionRepository.java
  src/main/java/chungbazi/chungbazi_be/domain/member/repository/MemberInterestRepository.java
  src/main/java/chungbazi/chungbazi_be/domain/member/repository/MemberRepository.java
  src/main/java/chungbazi/chungbazi_be/domain/member/service/MemberService.java
  src/main/java/chungbazi/chungbazi_be/domain/user/UserHandler.java
  src/main/java/chungbazi/chungbazi_be/domain/user/controller/UserController.java
  src/main/java/chungbazi/chungbazi_be/domain/user/converter/UserConverter.java
  src/main/java/chungbazi/chungbazi_be/domain/user/dto/UserRequestDTO.java
  src/main/java/chungbazi/chungbazi_be/domain/user/dto/UserResponseDTO.java
  src/main/java/chungbazi/chungbazi_be/domain/user/entity/Addition.java
  src/main/java/chungbazi/chungbazi_be/domain/user/entity/Interest.java
  src/main/java/chungbazi/chungbazi_be/domain/user/entity/User.java
  src/main/java/chungbazi/chungbazi_be/domain/user/entity/enums/Education.java
  src/main/java/chungbazi/chungbazi_be/domain/user/entity/enums/Employment.java
  src/main/java/chungbazi/chungbazi_be/domain/user/entity/enums/Gender.java
  src/main/java/chungbazi/chungbazi_be/domain/user/entity/enums/Income.java
  src/main/java/chungbazi/chungbazi_be/domain/user/entity/enums/OAuthProvider.java
  src/main/java/chungbazi/chungbazi_be/domain/user/entity/enums/Region.java
  src/main/java/chungbazi/chungbazi_be/domain/user/entity/mapping/UserAddition.java
  src/main/java/chungbazi/chungbazi_be/domain/user/entity/mapping/UserInterest.java
  src/main/java/chungbazi/chungbazi_be/domain/user/repository/AdditionRepository.java
  src/main/java/chungbazi/chungbazi_be/domain/user/repository/InterestRepository.java
  src/main/java/chungbazi/chungbazi_be/domain/user/repository/UserAdditionRepository.java
  src/main/java/chungbazi/chungbazi_be/domain/user/repository/UserInterestRepository.java
  src/main/java/chungbazi/chungbazi_be/domain/user/repository/UserRepository.java
  src/main/java/chungbazi/chungbazi_be/domain/user/service/UserService.java
  src/main/java/chungbazi/chungbazi_be/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/chungbazi/chungbazi_be/global/config/SecurityConfig.java
Labels: :bug: fix, 🛠 feature

#27 [feature] 공통 handler 처리 및 공통 URL 경로 설정
  .gitignore
  src/main/java/chungbazi/chungbazi_be/domain/user/controller/UserController.java
  src/main/java/chungbazi/chungbazi_be/domain/user/entity/enums/Gender.java
  src/main/java/chungbazi/chungbazi_be/domain/user/service/UserService.java
  src/main/java/chungbazi/chungbazi_be/global/apiPayload/exception/handler/BadRequestHandler.java
  src/main/java/chungbazi/chungbazi_be/global/apiPayload/exception/handler/NotFoundHandler.java
  src/main/java/chungbazi/chungbazi_be/global/apiPayload/exception/handler/UserHandler.java
  src/main/java/chungbazi/chungbazi_be/global/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: 🛠 feature

#29 [chore] cicd 구축, 배포, 도커 설정
  .github/workflows/deploy.yml
  Dockerfile
  build.gradle
  src/main/resources/application.yml
Labels: ⚙ chore

#30 [feature] 알림 생성&알림 읽음 변경 로직 구현 (#20)
  build.gradle
  src/main/generated/chungbazi/chungbazi_be/domain/notification/entity/QNotification.java
  src/main/generated/chungbazi/chungbazi_be/domain/user/entity/QUser.java
  src/main/java/chungbazi/chungbazi_be/domain/notification/controller/NotificationController.java
  src/main/java/chungbazi/chungbazi_be/domain/notification/dto/NotificationRequestDTO.java
  src/main/java/chungbazi/chungbazi_be/domain/notification/dto/NotificationResponseDTO.java
  src/main/java/chungbazi/chungbazi_be/domain/notification/entity/Notification.java
  src/main/java/chungbazi/chungbazi_be/domain/notification/entity/enums/NotificationType.java
  src/main/java/chungbazi/chungbazi_be/domain/notification/repository/NotificationRepository.java
  src/main/java/chungbazi/chungbazi_be/domain/notification/service/FCMTokenService.java
  src/main/java/chungbazi/chungbazi_be/domain/notification/service/NotificationService.java
  src/main/java/chungbazi/chungbazi_be/domain/user/entity/User.java
  src/main/java/chungbazi/chungbazi_be/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/chungbazi/chungbazi_be/global/apiPayload/exception/handler/NotificationHandler.java
Labels: 🛠 feature

#31 [feature] 카카오 로그인 구현
  build.gradle
  src/main/java/chungbazi/chungbazi_be/domain/auth/controller/KakaoAuthController.java
  src/main/java/chungbazi/chungbazi_be/domain/auth/dto/TokenDTO.java
  src/main/java/chungbazi/chungbazi_be/domain/auth/dto/TokenRequestDTO.java
  src/main/java/chungbazi/chungbazi_be/domain/auth/dto/TokenResponseDTO.java
  src/main/java/chungbazi/chungbazi_be/domain/auth/jwt/AuthUserArgumentResolver.java
  src/main/java/chungbazi/chungbazi_be/domain/auth/jwt/CookieUtil.java
  src/main/java/chungbazi/chungbazi_be/domain/auth/jwt/CustomAccessDeniedHandler.java
  src/main/java/chungbazi/chungbazi_be/domain/auth/jwt/CustomAuthenticationEntryPoint.java
  src/main/java/chungbazi/chungbazi_be/domain/auth/jwt/JwtAuthenticationToken.java
  src/main/java/chungbazi/chungbazi_be/domain/auth/jwt/JwtTokenFilter.java
  src/main/java/chungbazi/chungbazi_be/domain/auth/jwt/JwtUtil.java
  src/main/java/chungbazi/chungbazi_be/domain/auth/jwt/TokenGenerator.java
  src/main/java/chungbazi/chungbazi_be/domain/auth/service/CustomUserDetailsService.java
  src/main/java/chungbazi/chungbazi_be/domain/auth/service/KakaoAuthService.java
  src/main/java/chungbazi/chungbazi_be/domain/auth/service/RedisTokenService.java
  src/main/java/chungbazi/chungbazi_be/domain/auth/service/TokenCookieService.java
  src/main/java/chungbazi/chungbazi_be/domain/policy/controller/PolicyController.java
  src/main/java/chungbazi/chungbazi_be/domain/policy/dto/PolicyListOneResponse.java
  src/main/java/chungbazi/chungbazi_be/domain/policy/dto/PolicySearchResponse.java
  src/main/java/chungbazi/chungbazi_be/domain/policy/dto/PopularSearchResponse.java
  src/main/java/chungbazi/chungbazi_be/domain/policy/dto/YouthPolicyListResponse.java
  src/main/java/chungbazi/chungbazi_be/domain/policy/dto/YouthPolicyResponse.java
  src/main/java/chungbazi/chungbazi_be/domain/policy/entity/Category.java
  src/main/java/chungbazi/chungbazi_be/domain/policy/entity/Policy.java
  src/main/java/chungbazi/chungbazi_be/domain/policy/repository/PolicyRepository.java
  src/main/java/chungbazi/chungbazi_be/domain/policy/repository/PolicyRepositoryCustom.java
  src/main/java/chungbazi/chungbazi_be/domain/policy/repository/PolicyRepositoryImpl.java
  src/main/java/chungbazi/chungbazi_be/domain/policy/service/PolicyService.java
  src/main/java/chungbazi/chungbazi_be/domain/user/controller/UserController.java
  src/main/java/chungbazi/chungbazi_be/domain/user/dto/UserRequestDTO.java
  src/main/java/chungbazi/chungbazi_be/domain/user/dto/UserResponseDTO.java
  src/main/java/chungbazi/chungbazi_be/domain/user/entity/User.java
  src/main/java/chungbazi/chungbazi_be/domain/user/entity/enums/Gender.java
  src/main/java/chungbazi/chungbazi_be/domain/user/repository/UserRepository.java
  src/main/java/chungbazi/chungbazi_be/domain/user/service/UserService.java
  src/main/java/chungbazi/chungbazi_be/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/chungbazi/chungbazi_be/global/apiPayload/exception/handler/UnAuthorizedHandler.java
  src/main/java/chungbazi/chungbazi_be/global/config/ClientConfig.java
  src/main/java/chungbazi/chungbazi_be/global/config/SecurityConfig.java
  src/main/java/chungbazi/chungbazi_be/global/config/WebMvcConfig.java
  src/main/java/chungbazi/chungbazi_be/global/validation/RegexConstants.java
  src/main/java/chungbazi/chungbazi_be/global/validation/annotation/AuthUser.java
  src/main/resources/application.yml
Labels: 🛠 feature

#37 [feature] Security 통해 userId 반환
  src/main/java/chungbazi/chungbazi_be/domain/auth/jwt/SecurityUtils.java
  src/main/java/chungbazi/chungbazi_be/domain/user/controller/UserController.java
  src/main/java/chungbazi/chungbazi_be/domain/user/service/UserService.java
Labels: 🛠 feature

#40 [feature] 마이페이지 유저 정보 수정
  build.gradle
  src/main/generated/chungbazi/chungbazi_be/domain/notification/entity/QNotification.java
  src/main/generated/chungbazi/chungbazi_be/domain/user/entity/QUser.java
  src/main/generated/chungbazi/chungbazi_be/domain/user/entity/mapping/QUserAddition.java
  src/main/generated/chungbazi/chungbazi_be/domain/user/entity/mapping/QUserInterest.java
  src/main/generated/chungbazi/chungbazi_be/global/entity/QUuid.java
  src/main/java/chungbazi/chungbazi_be/domain/user/controller/UserController.java
  src/main/java/chungbazi/chungbazi_be/domain/user/converter/UserConverter.java
  src/main/java/chungbazi/chungbazi_be/domain/user/dto/UserRequestDTO.java
  src/main/java/chungbazi/chungbazi_be/domain/user/dto/UserResponseDTO.java
  src/main/java/chungbazi/chungbazi_be/domain/user/entity/User.java
  src/main/java/chungbazi/chungbazi_be/domain/user/repository/UserRepository.java
  src/main/java/chungbazi/chungbazi_be/domain/user/service/UserService.java
  src/main/java/chungbazi/chungbazi_be/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/chungbazi/chungbazi_be/global/config/S3Confing.java
  src/main/java/chungbazi/chungbazi_be/global/config/WebConfig.java
  src/main/java/chungbazi/chungbazi_be/global/entity/Uuid.java
  src/main/java/chungbazi/chungbazi_be/global/repository/UuidRepository.java
  src/main/java/chungbazi/chungbazi_be/global/s3/OctetStreamReadMsgConverter.java
  src/main/java/chungbazi/chungbazi_be/global/s3/S3Manager.java
  src/main/resources/application.yml
Labels: 🛠 feature
